apiVersion: v1
kind: Pod
metadata:
  name: product-pod
spec:
  containers:
    - name: product
      image: jpcassidy/productservice:latest
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
      ports:
        - containerPort: 8080
