apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-chart.fullname" . }}
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "product-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "product-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "product-chart.fullname" . }}-configmap
                  key: log_level
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "product-chart.fullname" . }}-secret
                  key: api_key
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
---
# FILEPATH: /c:/DEV/github.com/CloudNative/orchestrators/k8s/product-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-chart.fullname" . }}-service
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "product-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
# FILEPATH: /c:/DEV/github.com/CloudNative/orchestrators/k8s/product-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "product-chart.fullname" . }}-ingress
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: '{{ .Values.ingress.path }}'
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "product-chart.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
---
# FILEPATH: /c:/DEV/github.com/CloudNative/orchestrators/k8s/product-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-chart.fullname" . }}-configmap
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
data:
  log_level: {{ .Values.configMap.logLevel }}
---
# FILEPATH: /c:/DEV/github.com/CloudNative/orchestrators/k8s/product-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-chart.fullname" . }}-secret
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.secret.apiKey }}
